### ISSUE TITLE
Don't include options with value undefined in URL parameters

### ISSUE THREAD

**Issue by Niels-NTG** [reststate/reststate-vuex#37]
Below I have a situation where by default the data doesn't have any special sorting applied to it. `this.sort` is still `undefined` at this point, yet it passed in the URL as a parameter `GET /organisation/1/products?page=1&itemsPerPage=10&sort=undefined`. While an argument can be made to still include the falsely values `false`, `0` and `null`, I don't think `undefined` should be included when creating the URL parameters.
```js
    data() {
        return {
            currentPage: 1,
            itemsPerPage: 10,
            sort: undefined
        }
    },

    methods: {
        loadProducts() {
            this.$store.dispatch('products/loadRelated', {
                parent: {
                    id: this.organisationlId,
                    type: 'organisation'
                },
                options: {
                    page: this.currentPage,
                    itemsPerPage: this.itemsPerPage,
                    sort: this.sort
                }
            })
        },
```

**Comment by CodingItWrong** [comment]
This makes sense and should be pretty straightforward. I am preparing for a meetup presentation tonight but I should be able to get to this in the next few days.

**Comment by CodingItWrong** [comment]
OK, this functionality actually lives in `@reststate/client`. I've fixed it in https://github.com/reststate/reststate-client/pull/18 and released `@reststate/client` version `0.0.7`. If you update to it, you should see `undefined` options excluded from the query string.

**Comment by Niels-NTG** [comment]
I've added `"@reststate/client": "0.0.7"`to my package but it doesn't resolve the issue.

**Comment by Niels-NTG** [comment]
I think it has something to do with how values in Vue's `data()` method are stored.

**Comment by Niels-NTG** [comment]
Or you just need to release an update for `reststate/reststate-vuex`

**Comment by CodingItWrong** [comment]
The newly released `@reststate/vuex@0.0.15` should force the correct dependency
