### ISSUE TITLE
Page getter return old data after loadPage options change

### ISSUE THREAD

**Issue by Niels-NTG** [reststate/reststate-vuex#39]
Same issue as https://github.com/reststate/reststate-vuex/issues/34, except that this time it's not possible to supply options to the getter.

For example:
```js
    computed: {
        products() {
            // Cannot add options to /page since it's not a function
            const products = this.$store.getters['products/page'] || []
            // return products formatted for table
            return products.map(({attributes}) => attributes)
        }
    },

   methods: {
        loadProducts() {
            // Load products for the current page number.
            this.$store.dispatch('products/loadPage', {
                options: {
                    page: this.currentPage,
                    itemsPerPage: this.itemsPerPage,
                    sort: this.sort
                }
            }).then(() => {
                const meta = this.$store.getters['products/lastMeta']
                this.totalItems = meta.totalItems
            })
        }
  }
```

**Comment by CodingItWrong** [comment]
Ok, I've fixed a bug in #44 where the page records were returned out of order, so that should fix the problem where changing the sort order didn't take effect. It's released as `0.0.16`

Based on the way the `page` getter is implemented, you won't actually need to pass the options to it; it's already set up to be automatically updated each time you make a `loadPage` request, so you don't need to pass options to change the cached value that is loaded. The test I added for #44 confirms this.

So with the fix in `0.0.16` you should see that making a `loadPage` request with new sort options affects the results of the `page` getter. Update to `0.0.16` and give that a try.

**Comment by Niels-NTG** [comment]
This doesn't seem to fix it for pages where the amount of items is less or equal to size of the page.

**Comment by CodingItWrong** [comment]
I'm not sure why that would be. I think your best bet to troubleshoot would be to debug what exactly is happening:

- Is the Ajax request being sent?
- Are the records saved into the store?
- Are the IDs of the records returned saved into the store `page` property in the new updated order?

**Comment by Niels-NTG** [comment]
Request are being sent, something is trigged to update the store, but its order isn't updated.

**Comment by CodingItWrong** [comment]
OK, to help track this down, what is the order of the IDs:

1. Returned in the web service response?
2. Stored by the `STORE_PAGE` mutation into the `page` state property?
3. Returned by the `page` getter?

**Comment by CodingItWrong** [comment]
(If you haven't used Vue Devtools before, you can use them to inspect what's going on with the store: https://github.com/vuejs/vue-devtools)

**Comment by Niels-NTG** [comment]
Okay. This is bizarre. The very act of adding some `console.log` to the reststate-vuex library solved the problem… I've disabled caching while Chrome devtools are open so I suspect that I have to change something in the Vue CLI settings. 😑 Sorry to have wasted your time.

**Comment by CodingItWrong** [comment]
Oh, no need to apologize, I'm glad to help. That sounds like a very strange situation. I hope it's working well for you now
